services:
    sonata.admin.item:
        class: GBP\BacardiBundle\Admin\ItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Содержимое", label: "Вещи" }
        arguments:
            - ~
            - GBP\BacardiBundle\Entity\Item
            - ~
        calls:
            - [ setTranslationDomain, [GBPBacardiBundle]]
    sonata.admin.employee:
        class: GBP\BacardiBundle\Admin\EmployeeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Содержимое", label: "Сотрудники" }
        arguments:
            - ~
            - GBP\BacardiBundle\Entity\Employee
            - ~
        calls:
            - [ setTranslationDomain, [GBPBacardiBundle]]
    sonata.admin.category:
        class: GBP\BacardiBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Содержимое", label: "Категории" }
        arguments:
            - ~
            - GBP\BacardiBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [GBPBacardiBundle]]

    sonata.admin.itemtype:
        class: GBP\BacardiBundle\Admin\ItemTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Содержимое", label: "Типы вещей" }
        arguments:
            - ~
            - GBP\BacardiBundle\Entity\ItemType
            - ~
        calls:
            - [ setTranslationDomain, [GBPBacardiBundle]]